### ISSUE TITLE
RMagick never releases the Global VM Lock

### ISSUE THREAD

**Issue by thedrow** [rmagick/rmagick#243]
It'd be awesome to be able to be able to process images in parallel without resorting to multiple processes when they are not needed.
Let's start mapping long running operations in C that make it worth releasing the GVL.

**Comment by thedrow** [comment]
See #244 for releasing the GVL on ImageList operations.

**Comment by mockdeep** [comment]
See https://github.com/rmagick/rmagick/pull/304 for the latest PR.

**Comment by Watson1978** [comment]
We don't touch any Ruby C APIs while unlocking GVL.

`rm_check_exception()` might use Ruby C API to raise exception. it should not.

**Comment by Watson1978** [comment]
The monitor feature accepts ImageMagick callbacks.
If the callback runs without GVL, it will cause a SEGV.
https://github.com/rmagick/rmagick/pull/1253

So, to release GVL, I think we need to drop monitor feature.

**Comment by jdelStrother** [comment]
Seems like the previous PRs for this didn't make it because there wasn't suitable test infrastructure - has that changed?

FWIW I've been experimenting with unlocking the GVL around ReadImage & ImageToBlob [here](https://github.com/rmagick/rmagick/compare/main...jdelStrother:gvl), which seem to work well as long as you're not using monitors.

We're using those two methods in a threaded Rails app with puma. It _hasn't_ greatly increased performance of, say, multiple parallel image reads. But it has reduced the effect those image requests would have on unrelated requests running on different threads, where otherwise fast requests would occasionally stall due to RMagick blocking the GVL.

**Comment by jdelStrother** [comment]
I see ruby-pg have a clever [macro-based thing](https://github.com/ged/ruby-pg/blob/9b7909d3d78c6ba2780427fab106d7c215ca300f/ext/gvl_wrappers.h) to deal with all the unlocking for them - given a function like `PQconnectdb(conninfo)`, they just call `gvl_PQconnectdb(conninfo)` and the macro deals with setting up a struct for passing the arguments.
As with all c macros, they're somewhat incomprehensible, but if we took that approach it would mean the changes to the rest of the codebase are pretty minimal. It also means you can opt and and out by setting a ENABLE_GVL_UNLOCK configure flag.

That said, they are planning on removing the GVL-unlock support as they move to Fiber scheduling (https://github.com/ged/ruby-pg/pull/397) ... though I guess their situation is a little different since postgres supplies async c functions for them to call, whereas all of imagemagick is synchronous, right?
