### ISSUE TITLE
Support for pango: in ImageMagick

### ISSUE THREAD

**Issue by ottermix** [rmagick/rmagick#274]
I am having some issues getting RTL and Arabic characters to work correctly.  They don't appear connected.  The solutions often suggest using `pango:@text.txt` in the `convert` command line but I don't think there is any way to add "pango" text with `Magick::Draw` am I right?  Is there a way to implement RTL / connected text like Arabic / Urdu / Farsi / etc?

**Comment by laddhadhiraj** [comment]
yes, is any solution for it! I am also trying to print colored emoji  with image

**Comment by Watson1978** [comment]
### setup
1. install `pango` library (ex `brew install pango`)
2. build ImageMagick 6 from source code
```
$ curl -O https://imagemagick.org/download/ImageMagick-6.9.10-84.tar.xz
$ tar xvJf ImageMagick-6.9.10-84.tar.xz
$ cd ImageMagick-6.9.10-84
$ ./configure --with-pango
$ make install
```

### code
```
require 'rmagick'

img = Magick::Image.read('pango:Some  <span size="49152" rise="-20480" foreground="red" background="blue"> Big Red on Blue </span>  Text').first
img.write('test.png')
```

or

```
require 'rmagick'

img = Magick::Image.read('pango:@sample.pango').first
img.write('test.png')
```

**Comment by VladFomenko** [comment]
Hello! I have a problem
I can use pango only in Magick::Image.read as a parameter
```
image = Magick::Image.read("pango:#{text}") do |img|
 img.size = '900x800'
 img.background_color = 'none' 
 img.pointsize = font_size # dynamic font
 img.font = some_font_type
 img.fill = 'white' # font color
 img.gravity = Magick::CenterGravity
 img.define('pango', 'markup', 'false')
end
image.write('output.png')
```

but the problem is that I need to count the length of the text, to dynamically calculate the font size

```
image = Magick::Image.new(900, 800)
draw = Magick::Draw.new
draw.font = some_font_type
draw.pointsize = 78
draw.fill('white')
draw.gravity = Magick::CenterGravity
draw.get_type_metrics(image, text)
draw.annotate(image, 0, 0, 0, 0, text)
image.write('output2.png')
```

and it turns out that I count through
and the output between caption(in Magick::Draw.new) and pango(Magick::Image.read) is different. And I can't correctly calculate the text width for the dynamic font definition.
![image](https://github.com/rmagick/rmagick/assets/41300309/aea72a4e-1805-4dbe-acaf-8360679fb5c7)
![image](https://github.com/rmagick/rmagick/assets/41300309/f1064c8a-5e41-4a39-8c2c-cf859549cfd7)
do not pay attention to the fact that the text has slipped out, but the difference in the dimensions of the text is clearly visible.
And I need to somehow calculate the width of the ribbon in pango, to understand that I need to give a smaller font size so that all the text fits into my box.

please help :)

**Comment by Watson1978** [comment]
you can calculate the approximate width needed for rendering using `Draw#get_type_metrics`.
pango seems to have a different rendering mechanism, or perhaps there is a subtle difference.

```ruby
require 'rmagick'

TEXT = "hello this beautiful world you are perfect with pango"
FONT_SIZE = 90
FONT_TYPE = nil # some_font_type

def font_size(text, width, font: nil, max_font_size: 100)
  image = Magick::Image.new(100, width)
  draw = Magick::Draw.new

  max_font_size.downto(1) do |pointsize|
    draw.push
    draw.font = font if font
    draw.pointsize = pointsize
    metrics = draw.get_type_metrics(image, text)
    draw.pop
    if metrics.width < width
      # To avoid overflow when actually rendered.
      return (pointsize > 3) ? pointsize - 3 : 1
    end
  end

  1
end

image = Magick::Image.read("pango:#{TEXT}") do |img|
  img.size = '900x800'
  img.background_color = 'none' 
  img.pointsize = font_size(TEXT, 800, font: FONT_TYPE) # dynamic font
  # img.font = FONT_TYPE
  img.fill = 'white' # font color
  img.gravity = Magick::CenterGravity
  img.define('pango', 'markup', 'false')
end
image.first.write('output.png')
```
