### ISSUE TITLE
Image#iptc_profile does not work on ImageMagick 6.7

### ISSUE THREAD

**Issue by Watson1978** [rmagick/rmagick#554]
* Reproduce

```
     404:     assert_nothing_raised { @img.iptc_profile = 'xxx' }
  => 405:     assert_equal('xxx', @img.iptc_profile)
<"xxx"> expected but was
<nil>
```

**Comment by dlemstra** [comment]
I figured out what is causing this issue. The `iptc` profile is stored as the `8bim` profile and that means that `iptc_profile` will not call `ProfileImage` because of this check: https://github.com/rmagick/rmagick/blob/master/ext/RMagick/rmimage.c#L2638. This was a bug in that old version of ImageMagick and has been fixed in more recent versions. You probably need a version check for that assert.

**Comment by Watson1978** [comment]
@dlemstra Thank you for your hard work!
