### ISSUE TITLE
Image draw hangs

### ISSUE THREAD

**Issue by SigmaDev1** [rmagick/rmagick#600]
Sometimes when trying to draw and save the image, it hangs with out any errors.

**Comment by SigmaDev1** [comment]
def render_solid_background(color)
      Image.new(@columns, @rows) {
        self.background_color = color
      }
    end

@base_image = render_solid_background(@theme_options[:background_colors])
    def write(filename='graph.png')
      draw
      @base_image.write(filename)      
    end
https://github.com/topfunky/gruff/blob/master/lib/gruff/base.rb

**Comment by Watson1978** [comment]
`gruff` targets old rmagick.
```
    s.add_dependency 'rmagick', '~> 2.13', '>= 2.13.4'
```

It should update.

**Comment by mockdeep** [comment]
@SigmaDev1 thanks for reporting. Unfortunately, `gruff` hasn't been updated in several years and is not up to date with the latest version of RMagick. This is probably fixed in the latest version of RMagick, so I'm going to close this, but feel free to open a new issue if you are able to reproduce it in RMagick >= 3.1.
