### ISSUE TITLE
Documentation missing: Attributes #columns, #rows, #colors, … in Magick::Image 

### ISSUE THREAD

**Issue by Lapizistik** [rmagick/rmagick#784]
The generated rdoc of Magick::Image seems to miss attributes/methods, e.g. Magick::Image#columns, Magick::Image#rows and Magick::Image::colors exist and work but do not show up in the documentation (which is kinda annoying).
Is this by design?

Thanks for your work!

**Comment by mockdeep** [comment]
@Lapizistik this is not by design, but by simple lack of engineering resources. If you're so inclined, a PR would be very welcome.

**Comment by Lapizistik** [comment]
I am currently stuck.
I try to document below what I found, so maybe someone else can use this (or give me a hint).
### Temporary fix
Currently the _documentation_ link on [rubygems.org](https://rubygems.org/gems/rmagick/) points to the [README](https://www.rubydoc.info/gems/rmagick/) of the auto-generated documentation.
- There is no hint in the README or on [rubygems.org](https://rubygems.org/gems/rmagick/) that [rmagick.github.io](http://rmagick.github.io) exists
  - seems to be outdated?
  - the attributes are documented there
- So including a link to [rmagick.github.io](http://rmagick.github.io) in the README could help.

### Current state of documentation
- All methods (including attribute readers) are documented in the C sources
- The documentation style looks similar to yard but has differences:
  - I assume it is [Doxygen](http://www.doxygen.nl/)
    - There is a Doxyfile in the root folder
    - Some of the tags used (like `@verbatim`) are ignored by yard but documented for doxygen
  - But [rubygems.org](https://rubygems.org) autogenerates documentation on [www.rubydoc.info](http://www.rubydoc.info/gems/rmagick/) using yard
  - Therefore the generated docs are full of `@verbatim` … `@endverbatim` etc.
  - and there are incomplete (without giving any hint about this)
- yard does not generate documentation for at least two cases:
  - When macros are used:
    - The C macro `DEF_ATTR_READER` is e.g. used for `colors`, `columns`, `rows`, …,
    - `DEF_ATTR_ACCESSOR` for `delay`, …
  - When getter and setter are defined using `_eq` (perhaps also in other cases, not sure about this):
    - For example, `Image_bias` and `Image_bias_eq` are both not documented
    - but `Image_add_noise` is (so it is not just having an extra `_`)
    - and `Image_base_columns`, `Image_base_filename`, `Image_base_rows` are not
- Customizing yard did not work (at least I was not able to do it)
  - In general it should be possible to provide custom yard extensions through `.yardopts` (but I am not sure whether [www.rubydoc.info](https://www.rubydoc.info) would respect this.
  - I tried to write a custom `YARD::Handlers::C::AttributeHandler` for the macro `DEF_ATTR_READER` but could not figure out how to get this working (and there is nearly no documentation on how to do this for C code).
  - Using `yard --tag verbatim --hide-tag verbatim` etc. to suppress these tags does not work, as yard demands tags to be at the beginning of the line, therefore `@verbatim` is not caught at all.

### Questions
- Will `doxygen` be used in the future for processing the sources?
  - Even though the auto-generated documentation on [www.rubydoc.info](http://www.rubydoc.info/gems/rmagick/) is processed by `yard`(and we cannot(?) change this)
  - Or could we change the sources to get valid yard documentation? 
- I assume (parts of) [rmagick.github.io](http://rmagick.github.io) was generated from the sources by doxygen?
  - Does this still hold for the current version (as the documentation is held as an extra project and fairly outdated etc)?
  - What kind of documentation does the project want?
- Is there anyone who knows how to process C macros with yard? ;-)

### Thanks
Thank a lot for your work!

**Comment by mockdeep** [comment]
@Lapizistik Wow! Thanks for doing so much digging into this!

> Will `doxygen` be used in the future for processing the sources?

I haven't thought about it very deeply, but I think it would probably make more sense to convert things over to `yard` or `rdoc` instead at some point.

> I assume (parts of) [rmagick.github.io](http://rmagick.github.io) was generated from the sources by doxygen?

I'm honestly not at all familiar with how the documentation was generated. Right now it is just statically hosted from the documentation github repo: https://github.com/rmagick/rmagick.github.io, but it looks like it was probably auto-generated, so maybe your suspicion about doxygen is correct.

> Does this still hold for the current version (as the documentation is held as an extra project and fairly outdated etc)?

No, we don't have any process for updating the docs at this point, so those haven't been updated in several years.

> What kind of documentation does the project want?

I think the ideal would be something like in-line yard docs. That way they're easier to keep up to date. In terms of documentation in general, I think above all we would want it in a format that is easier to keep up to date than what we currently have. If you're willing to contribute your time, I think we would gladly defer to your discretion on a lot of these kinds of questions, though.

> Is there anyone who knows how to process C macros with yard?

Hmm, not sure how to handle this. I thought the [ruby-pg gem](https://github.com/ged/ruby-pg) might be a good reference, but they use [very few macros](https://github.com/ged/ruby-pg/search?p=1&q=%22%5C%23define%22&type=Code&unscoped_q=%22%5C%23define%22), so that doesn't seem to helpful. Maybe it's worth thinking if there's a way to refactor the code for easier documentation. I'll poke around some more and see if I can find any other C API gems for reference.

> Thank a lot for your work!

Thank you! You've opened up an important conversation, and anything you can contribute would be very much valued.

**Comment by Lapizistik** [comment]
I had some deeper look into yard.
### The problem
I found out how to write custom handlers for C code comments, but this does not help.
The big problem is that the yard parser for the C code gets confused by the macros:
- it assumes that a toplevel statement ends with `{` or `;`
- therefore the definition _following_ the macro gets consumed by the parser (this explains why the documentation for other methods was missing, too)
- fixing this would need big changes in the yard C parser core (I assume the easiest and most powerful approach would be to run a C preprocessor before generating the documentation)
- so this is outside the scope of RMagick
### Suggested fixes
1. Replace the macros with their definition:
    - The attribute macros are all one-liners (see [rmagick.h](https://github.com/rmagick/rmagick/blob/c299613f1c61fd46b2004f78ee9a8eb5e47dab0c/ext/RMagick/rmagick.h#L390)), so this should not be a problem regarding readability
    - This should at least bring back the documentation for all the methods and attributes currently missing (with doxygen tags like `@verbatim` in it as plain text, not pretty but useable)
2. Change doxygen tags to yard tags
    - delete `@verbatim` and `@endverbatim` tags (or change `@verbatim … @endverbatim` to `**…**` where appropriate)
    - improve `@param` declarations:
      - remove `@param class …` statements (yard automagically converts the C style method to ruby OO style)
      - join `@param argc` and `@param argv` to `@param *args` (more yard magic). But: see below
      - find replacements for other doxygen tags
      - fix indentation: there are lots of indented lists (which are shown as `<pre>` code blocks by yard)
    - rewrite (simplify) the comments:
      - many of the “Ruby usage” blocks may not longer be necessary 
        - yard magic creates correct ruby method signatures from the C code
        - for methods with optional parameters (`some_method(*args)`) yard has special syntax to describe these in a ruby-like way.
      - make them more rubyesque
3. Include additional documentation
    - include the tutorials from https://rmagick.github.io/ as extra files
    - integrate them with the generated api docs
    - this is long-term

**Comment by mockdeep** [comment]
> Unfortunately this decreases readability. Perhaps they could be replaced by better code?

Yeah, I'm surprised there isn't a cleaner way of accomplishing this. Do you have specific ideas? Something else I came across was [this issue comment](https://github.com/lsegal/yard/issues/823#issuecomment-68424571), which describes a `@!parse` syntax for overriding the default behavior. Not sure if that would work in this case or not.

I think your suggestions all sound pretty reasonable. Feel free to start putting in some exploratory PRs if you're inclined. One note, though, is that it would be good to start with some smaller changes so that it's easier to review and discuss.

**Comment by Lapizistik** [comment]
I played around with these yard directives but achieved nothing useful.
I am not a C guy at all (as well as not familiar with the C side of ruby) and therefore would refrain from touching the C code. But I stay subscribed on this issue and may be back ;-)
