### ISSUE TITLE
Intermittent failure on Ubuntu 16.04

### ISSUE THREAD

**Issue by wkirby** [rmagick/rmagick#910]
I am seeing an intermittent failure running `rmagick` in a Rails 3.2 project on Ubuntu 16.04. The code works ~50% of the time, so I don't believe it's a problem with `rmagick` — I'm mostly here to find out if there's a way to get more information about the error.

```
(FailedToExecuteCommand `"gs" -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=pngalpha" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r150x150"  "-sOutputFile=/tmp/magick-1Jdj4rockdAC9%d" "-f/tmp/magick-1qWIidG5isS5x" "-f/tmp/magick-12TyAjmwYabzW"' (-1) @ error/delegate.c/ExternalDelegateCommand/461):
```

The relevant ruby stacktrace is:

```
  rmagick (2.16.0) lib/rmagick_internal.rb:1605:in `from_blob'
  rmagick (2.16.0) lib/rmagick_internal.rb:1605:in `block in from_blob'
  rmagick (2.16.0) lib/rmagick_internal.rb:1604:in `each'
  rmagick (2.16.0) lib/rmagick_internal.rb:1604:in `from_blob'
  app/services/pdf/pdf_service.rb:54:in `generate_images'
```

Searching for this error, the only reason I can find reported elsewhere is a problem with the `gs` binary on OSX. Because the code works, I'm pretty certain that is not the issue.

I'm hoping to find some way to output logs from ImageMagick and ghostscript directly. I've tried setting the `MAGICK_DEBUG=all` environment variable, but that appears to have no effect — ideally some way to pass `-dDEBUG` to the underlying `gs` call.

Thanks in advance for any help.

**Comment by mockdeep** [comment]
@wkirby is there a particular PDF file that triggers this consistently? In my experience, sometimes users upload PDFs that are in some way corrupted and cause ghostscript to barf. If you can isolate it to a specific file, you can try running the `gs` command from the error directly to get useful output.

I believe ghostscript prints the errors to `STDERR`, so if you're not capturing that you may want to have another look. It doesn't look like the command above filters the body of the error, but @Watson1978 or @dlemstra might have a better idea how you can get more of the error message.

**Comment by wkirby** [comment]
@mockdeep thanks for the response. Unfortunately no — I can get the error to happen or not happen with the same PDF blob. I would like to capture the temp files that are referenced in the error above, but Imagemagick appears to clean them up almost instantly, and I’ve found no documentation on keeping them around.

**Comment by mockdeep** [comment]
@wkirby I just noticed that you're running rmagick version 2.16.0. Unfortunately, we don't support that version anymore. One distinct possibility is that you're running into memory issues, since there were a lot of memory leaks in the older versions. A lot of work has been done since then to fix the issues. Is there any way you can upgrade to 4.x?

**Comment by wkirby** [comment]
@mockdeep I would love to. We are in the process of updating to Rails 4.6 (and hopefully onward to 5.2+), which should let us update. Appreciate your help and I'll close for now.

**Comment by wkirby** [comment]
@mockdeep I realize it's been almost 8 months, but I'm back. Our application is on to 4.x and we're still experiencing the same intermittent problem. I would love to find some way to get more information out of the system — are there any flags we can set to get error logs from imagemagick or rmagick that are closer to the source of the problem?

**Comment by mockdeep** [comment]
Hey @wkirby, Can you confirm that you're using RMagick version 4.1.2? I don't think there is any verbose flag you can apply to RMagick. Were you able to track down any more Ghostscript output in your logs? When we get a Ghostscript error in our application, there are usually a few lines of output. You could also try running the `gs` command that is output manually on the files you're processing.

If the issue is intermittent, it is probably something more related to resources. Are you able to reproduce it on your local machine, or does it only happen on production? If you're processing a lot of files, maybe your server's hard drive is filling up, in which case you may need to add a process to clear temp files regularly. It doesn't seem like memory should be an issue, but I'd check your monitoring for that as well. Another possibility is that there is some network issue. If you're pulling files from S3, it's often best to cache them on your server before trying to process them.

Unfortunately, without more information, it's hard to give more precise help. If you can post your code and an example file that triggers the issue, that might make it easier to reproduce. It might also help if you can give some more information about what services you're seeing this on, as in, your deployment environment.

**Comment by wkirby** [comment]
@mockdeep Thanks for the response. As far as I can tell there is not further GS output in the logs. I did end up setting some environment variables for ImageMagick (specifically `MAGICK_DEBUG="All"`) which didn't reveal much of anything. We are still seeing the same basic error from the initial post in this thread.

I totally agree with your assessment that the intermittent nature would lead me to believe that it's resource based, but all our server monitoring has shown absolutely nothing out of the ordinary: disk space utilization never above 20%, memory utilization never above 40%, CPU spikes occasionally but never above ~90% — and not in any way corresponding to the error.

I thought, for a while, that it might be related to ImageMagick resource policies, but that was quickly eliminated. Running `convert -list resource` shows:

```
  File       Area     Memory        Map       Disk   Thread  Throttle       Time
--------------------------------------------------------------------------------
786432   4.1135GB  1.9155GiB   3.831GiB  unlimited        2         0  unlimited
```

As for running the command manually, I have done so in a 1k-time loop and never saw the same error. Similarly, I have written a 1k-attempt loop to run as a `rake` task which exercises the same code path, and never experienced the issue there, either. As far as I can tell, the issue only occurs when the code is exercised through the Rails rendering stack — but again, intermittently.

As for local repro, I can reproduce it locally, but intermittently. The application is running inside a Docker container, though, so that's not really surprising — the local environment and the remote environment are all but identical.

At this point, I feel reasonably confident that it must be:

- A ghostscript issue (currently running `gs` `9.26`)
- An imagemagick issue (currently running `6.8.9-9`)
- An Ubuntu issue (currently running 16.04 because this is a legacy application that is essentially in maintenance mode)

I'm going to close this issue again because, ultimately, you've answered the question (there's not really a way to pass debug flags from our Ruby code down into the `gs` call). Once again, I appreciate your time in responding here, and all the work you and others have put into `rmagick`.

**Comment by alnguyen** [comment]
@wkirby I know it's been *several* years since this post--I am curious if you ever determined what the cause was or if you found a workaround for it?
